[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "dlh-dag-utils"
dynamic = ["version"]
description = "DAG Utilities for Data Lakehouse Automation"
requires-python = ">=3.11"
dependencies = []

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../.."
tag_regex = "^dlh-dag-utils-v(?P<version>.*)$"

[tool.hatch.build.targets.wheel]
packages = ["src/dlh"]
